language: android

android:
  components:
    - build-tools-20.0.0
    - android-20

install:
  - sudo apt-get install luarocks
  - sudo luarocks make

jdk: oraclejdk7

script:
  - non new "My Game"
  - non build desktop
  - non build android