language: android

android:
  components:
    - build-tools-21.1.2
    - android-20

install:
  - sudo apt-get install luajit
  - sudo apt-get install luarocks
  - sudo luarocks make non-dev-1.rockspec

jdk: oraclejdk7

script:
  - non -d hello moon
  - non -d build desktop
  - non -d build android